version: 3.7
services:
  couchdb:
    image: couchdb:3.3.3
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: ${COUCHDB_USER:-admin}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD:-password}
    volumes:
      - ./data:/opt/couchdb/data